(cl:defpackage minibot_msgs-srv
  (:use )
  (:export
   "ADDVISIBLEOBJECTS"
   "<ADDVISIBLEOBJECTS-REQUEST>"
   "ADDVISIBLEOBJECTS-REQUEST"
   "<ADDVISIBLEOBJECTS-RESPONSE>"
   "ADDVISIBLEOBJECTS-RESPONSE"
   "SEGMENT_SIGN_COMMAND"
   "<SEGMENT_SIGN_COMMAND-REQUEST>"
   "SEGMENT_SIGN_COMMAND-REQUEST"
   "<SEGMENT_SIGN_COMMAND-RESPONSE>"
   "SEGMENT_SIGN_COMMAND-RESPONSE"
   "SET_URL"
   "<SET_URL-REQUEST>"
   "SET_URL-REQUEST"
   "<SET_URL-RESPONSE>"
   "SET_URL-RESPONSE"
  ))

