// Generated by gencpp from file minibot_msgs/AddVisibleObjects.msg
// DO NOT EDIT!


#ifndef MINIBOT_MSGS_MESSAGE_ADDVISIBLEOBJECTS_H
#define MINIBOT_MSGS_MESSAGE_ADDVISIBLEOBJECTS_H

#include <ros/service_traits.h>


#include <minibot_msgs/AddVisibleObjectsRequest.h>
#include <minibot_msgs/AddVisibleObjectsResponse.h>


namespace minibot_msgs
{

struct AddVisibleObjects
{

typedef AddVisibleObjectsRequest Request;
typedef AddVisibleObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddVisibleObjects
} // namespace minibot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::minibot_msgs::AddVisibleObjects > {
  static const char* value()
  {
    return "e528cc6018453c0c96b68b36e0e306c9";
  }

  static const char* value(const ::minibot_msgs::AddVisibleObjects&) { return value(); }
};

template<>
struct DataType< ::minibot_msgs::AddVisibleObjects > {
  static const char* value()
  {
    return "minibot_msgs/AddVisibleObjects";
  }

  static const char* value(const ::minibot_msgs::AddVisibleObjects&) { return value(); }
};


// service_traits::MD5Sum< ::minibot_msgs::AddVisibleObjectsRequest> should match
// service_traits::MD5Sum< ::minibot_msgs::AddVisibleObjects >
template<>
struct MD5Sum< ::minibot_msgs::AddVisibleObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::minibot_msgs::AddVisibleObjects >::value();
  }
  static const char* value(const ::minibot_msgs::AddVisibleObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::minibot_msgs::AddVisibleObjectsRequest> should match
// service_traits::DataType< ::minibot_msgs::AddVisibleObjects >
template<>
struct DataType< ::minibot_msgs::AddVisibleObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::minibot_msgs::AddVisibleObjects >::value();
  }
  static const char* value(const ::minibot_msgs::AddVisibleObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::minibot_msgs::AddVisibleObjectsResponse> should match
// service_traits::MD5Sum< ::minibot_msgs::AddVisibleObjects >
template<>
struct MD5Sum< ::minibot_msgs::AddVisibleObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::minibot_msgs::AddVisibleObjects >::value();
  }
  static const char* value(const ::minibot_msgs::AddVisibleObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::minibot_msgs::AddVisibleObjectsResponse> should match
// service_traits::DataType< ::minibot_msgs::AddVisibleObjects >
template<>
struct DataType< ::minibot_msgs::AddVisibleObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::minibot_msgs::AddVisibleObjects >::value();
  }
  static const char* value(const ::minibot_msgs::AddVisibleObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINIBOT_MSGS_MESSAGE_ADDVISIBLEOBJECTS_H
