// Generated by gencpp from file minibot_msgs/segment_sign_command.msg
// DO NOT EDIT!


#ifndef MINIBOT_MSGS_MESSAGE_SEGMENT_SIGN_COMMAND_H
#define MINIBOT_MSGS_MESSAGE_SEGMENT_SIGN_COMMAND_H

#include <ros/service_traits.h>


#include <minibot_msgs/segment_sign_commandRequest.h>
#include <minibot_msgs/segment_sign_commandResponse.h>


namespace minibot_msgs
{

struct segment_sign_command
{

typedef segment_sign_commandRequest Request;
typedef segment_sign_commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct segment_sign_command
} // namespace minibot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::minibot_msgs::segment_sign_command > {
  static const char* value()
  {
    return "67dfdadbbb6dd9ac14fa405e04acf5b7";
  }

  static const char* value(const ::minibot_msgs::segment_sign_command&) { return value(); }
};

template<>
struct DataType< ::minibot_msgs::segment_sign_command > {
  static const char* value()
  {
    return "minibot_msgs/segment_sign_command";
  }

  static const char* value(const ::minibot_msgs::segment_sign_command&) { return value(); }
};


// service_traits::MD5Sum< ::minibot_msgs::segment_sign_commandRequest> should match
// service_traits::MD5Sum< ::minibot_msgs::segment_sign_command >
template<>
struct MD5Sum< ::minibot_msgs::segment_sign_commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::minibot_msgs::segment_sign_command >::value();
  }
  static const char* value(const ::minibot_msgs::segment_sign_commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::minibot_msgs::segment_sign_commandRequest> should match
// service_traits::DataType< ::minibot_msgs::segment_sign_command >
template<>
struct DataType< ::minibot_msgs::segment_sign_commandRequest>
{
  static const char* value()
  {
    return DataType< ::minibot_msgs::segment_sign_command >::value();
  }
  static const char* value(const ::minibot_msgs::segment_sign_commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::minibot_msgs::segment_sign_commandResponse> should match
// service_traits::MD5Sum< ::minibot_msgs::segment_sign_command >
template<>
struct MD5Sum< ::minibot_msgs::segment_sign_commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::minibot_msgs::segment_sign_command >::value();
  }
  static const char* value(const ::minibot_msgs::segment_sign_commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::minibot_msgs::segment_sign_commandResponse> should match
// service_traits::DataType< ::minibot_msgs::segment_sign_command >
template<>
struct DataType< ::minibot_msgs::segment_sign_commandResponse>
{
  static const char* value()
  {
    return DataType< ::minibot_msgs::segment_sign_command >::value();
  }
  static const char* value(const ::minibot_msgs::segment_sign_commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINIBOT_MSGS_MESSAGE_SEGMENT_SIGN_COMMAND_H
