// Generated by gencpp from file minibot_msgs/set_url.msg
// DO NOT EDIT!


#ifndef MINIBOT_MSGS_MESSAGE_SET_URL_H
#define MINIBOT_MSGS_MESSAGE_SET_URL_H

#include <ros/service_traits.h>


#include <minibot_msgs/set_urlRequest.h>
#include <minibot_msgs/set_urlResponse.h>


namespace minibot_msgs
{

struct set_url
{

typedef set_urlRequest Request;
typedef set_urlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_url
} // namespace minibot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::minibot_msgs::set_url > {
  static const char* value()
  {
    return "5a074a836c82adf8b27a048ee31b3a82";
  }

  static const char* value(const ::minibot_msgs::set_url&) { return value(); }
};

template<>
struct DataType< ::minibot_msgs::set_url > {
  static const char* value()
  {
    return "minibot_msgs/set_url";
  }

  static const char* value(const ::minibot_msgs::set_url&) { return value(); }
};


// service_traits::MD5Sum< ::minibot_msgs::set_urlRequest> should match
// service_traits::MD5Sum< ::minibot_msgs::set_url >
template<>
struct MD5Sum< ::minibot_msgs::set_urlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::minibot_msgs::set_url >::value();
  }
  static const char* value(const ::minibot_msgs::set_urlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::minibot_msgs::set_urlRequest> should match
// service_traits::DataType< ::minibot_msgs::set_url >
template<>
struct DataType< ::minibot_msgs::set_urlRequest>
{
  static const char* value()
  {
    return DataType< ::minibot_msgs::set_url >::value();
  }
  static const char* value(const ::minibot_msgs::set_urlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::minibot_msgs::set_urlResponse> should match
// service_traits::MD5Sum< ::minibot_msgs::set_url >
template<>
struct MD5Sum< ::minibot_msgs::set_urlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::minibot_msgs::set_url >::value();
  }
  static const char* value(const ::minibot_msgs::set_urlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::minibot_msgs::set_urlResponse> should match
// service_traits::DataType< ::minibot_msgs::set_url >
template<>
struct DataType< ::minibot_msgs::set_urlResponse>
{
  static const char* value()
  {
    return DataType< ::minibot_msgs::set_url >::value();
  }
  static const char* value(const ::minibot_msgs::set_urlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MINIBOT_MSGS_MESSAGE_SET_URL_H
