// Generated by gencpp from file minibot_msgs/set_urlRequest.msg
// DO NOT EDIT!


#ifndef MINIBOT_MSGS_MESSAGE_SET_URLREQUEST_H
#define MINIBOT_MSGS_MESSAGE_SET_URLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace minibot_msgs
{
template <class ContainerAllocator>
struct set_urlRequest_
{
  typedef set_urlRequest_<ContainerAllocator> Type;

  set_urlRequest_()
    : url()  {
    }
  set_urlRequest_(const ContainerAllocator& _alloc)
    : url(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _url_type;
  _url_type url;





  typedef boost::shared_ptr< ::minibot_msgs::set_urlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::minibot_msgs::set_urlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_urlRequest_

typedef ::minibot_msgs::set_urlRequest_<std::allocator<void> > set_urlRequest;

typedef boost::shared_ptr< ::minibot_msgs::set_urlRequest > set_urlRequestPtr;
typedef boost::shared_ptr< ::minibot_msgs::set_urlRequest const> set_urlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::minibot_msgs::set_urlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::minibot_msgs::set_urlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::minibot_msgs::set_urlRequest_<ContainerAllocator1> & lhs, const ::minibot_msgs::set_urlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.url == rhs.url;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::minibot_msgs::set_urlRequest_<ContainerAllocator1> & lhs, const ::minibot_msgs::set_urlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace minibot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::minibot_msgs::set_urlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::minibot_msgs::set_urlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minibot_msgs::set_urlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::minibot_msgs::set_urlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minibot_msgs::set_urlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::minibot_msgs::set_urlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::minibot_msgs::set_urlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b8fc5815211e556073b8281ccf07035";
  }

  static const char* value(const ::minibot_msgs::set_urlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b8fc5815211e556ULL;
  static const uint64_t static_value2 = 0x073b8281ccf07035ULL;
};

template<class ContainerAllocator>
struct DataType< ::minibot_msgs::set_urlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "minibot_msgs/set_urlRequest";
  }

  static const char* value(const ::minibot_msgs::set_urlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::minibot_msgs::set_urlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string url\n"
;
  }

  static const char* value(const ::minibot_msgs::set_urlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::minibot_msgs::set_urlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.url);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_urlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::minibot_msgs::set_urlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::minibot_msgs::set_urlRequest_<ContainerAllocator>& v)
  {
    s << indent << "url: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.url);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MINIBOT_MSGS_MESSAGE_SET_URLREQUEST_H
