// Generated by gencpp from file sphero_rvr_msgs/MoveToPosAndYawRequest.msg
// DO NOT EDIT!


#ifndef SPHERO_RVR_MSGS_MESSAGE_MOVETOPOSANDYAWREQUEST_H
#define SPHERO_RVR_MSGS_MESSAGE_MOVETOPOSANDYAWREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace sphero_rvr_msgs
{
template <class ContainerAllocator>
struct MoveToPosAndYawRequest_
{
  typedef MoveToPosAndYawRequest_<ContainerAllocator> Type;

  MoveToPosAndYawRequest_()
    : header()
    , position()
    , yaw(0.0)
    , speed(0.0)
    , speed_in_si(false)  {
    }
  MoveToPosAndYawRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , yaw(0.0)
    , speed(0.0)
    , speed_in_si(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _speed_type;
  _speed_type speed;

   typedef uint8_t _speed_in_si_type;
  _speed_in_si_type speed_in_si;





  typedef boost::shared_ptr< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPosAndYawRequest_

typedef ::sphero_rvr_msgs::MoveToPosAndYawRequest_<std::allocator<void> > MoveToPosAndYawRequest;

typedef boost::shared_ptr< ::sphero_rvr_msgs::MoveToPosAndYawRequest > MoveToPosAndYawRequestPtr;
typedef boost::shared_ptr< ::sphero_rvr_msgs::MoveToPosAndYawRequest const> MoveToPosAndYawRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator1> & lhs, const ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.yaw == rhs.yaw &&
    lhs.speed == rhs.speed &&
    lhs.speed_in_si == rhs.speed_in_si;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator1> & lhs, const ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sphero_rvr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5f177b95654adee39a774042679dd76";
  }

  static const char* value(const ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5f177b95654adeeULL;
  static const uint64_t static_value2 = 0x39a774042679dd76ULL;
};

template<class ContainerAllocator>
struct DataType< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sphero_rvr_msgs/MoveToPosAndYawRequest";
  }

  static const char* value(const ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point position\n"
"# yaw angle in radians\n"
"float32 yaw\n"
"float32 speed\n"
"# True if speed is in m/s, otherwise speed is in [0..128]\n"
"bool speed_in_si\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.yaw);
      stream.next(m.speed);
      stream.next(m.speed_in_si);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPosAndYawRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sphero_rvr_msgs::MoveToPosAndYawRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "speed_in_si: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed_in_si);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPHERO_RVR_MSGS_MESSAGE_MOVETOPOSANDYAWREQUEST_H
