// Generated by gencpp from file sphero_rvr_msgs/SetLedsResponse.msg
// DO NOT EDIT!


#ifndef SPHERO_RVR_MSGS_MESSAGE_SETLEDSRESPONSE_H
#define SPHERO_RVR_MSGS_MESSAGE_SETLEDSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sphero_rvr_msgs
{
template <class ContainerAllocator>
struct SetLedsResponse_
{
  typedef SetLedsResponse_<ContainerAllocator> Type;

  SetLedsResponse_()
    {
    }
  SetLedsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetLedsResponse_

typedef ::sphero_rvr_msgs::SetLedsResponse_<std::allocator<void> > SetLedsResponse;

typedef boost::shared_ptr< ::sphero_rvr_msgs::SetLedsResponse > SetLedsResponsePtr;
typedef boost::shared_ptr< ::sphero_rvr_msgs::SetLedsResponse const> SetLedsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace sphero_rvr_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sphero_rvr_msgs/SetLedsResponse";
  }

  static const char* value(const ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLedsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sphero_rvr_msgs::SetLedsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SPHERO_RVR_MSGS_MESSAGE_SETLEDSRESPONSE_H
